Repository yono-yuno/frontend, pull requests merged in 2025-03, with the labels that each got.

#6 [CHORE] 초기 설정 완료
  index.html
  public/yuno.png
  src/App.jsx
  src/apis/README.md
  src/assets/BackButton.png
  src/assets/Pretendard-Black.otf
  src/assets/Pretendard-Bold.otf
  src/assets/Pretendard-ExtraBold.otf
  src/assets/Pretendard-ExtraLight.otf
  src/assets/Pretendard-Light.otf
  src/assets/Pretendard-Medium.otf
  src/assets/Pretendard-Regular.otf
  src/assets/Pretendard-SemiBold.otf
  src/assets/Pretendard-Thin.otf
  src/assets/react.svg
  src/components/Button.jsx
  src/components/Header.jsx
  src/components/README.md
  src/hooks/README.md
  src/main.jsx
  src/pages/MainPage.jsx
  src/styles/App.css
  src/styles/index.css
  src/styles/style.css
  src/utils/README.md
  tailwind.config.js
Labels: enhancement

#18 [CHORE] 헤더 뒤로가기 버튼, 제목 위치 코드 변경
  src/components/Header.jsx
  src/styles/index.css
  tailwind.config.js
Labels: fix

#19 [DESIGN] 유저 관련 페이지
  src/App.jsx
  src/constants/Paths.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/utils/FormatByAuth.jsx
Labels: design

#24 [DESIGN] 쇼핑 관련 페이지
  package-lock.json
  package.json
  src/App.jsx
  src/assets/AllCategoryIcon.png
  src/assets/BabyCategoryIcon.png
  src/assets/BeautyCategoryIcon.png
  src/assets/BookCategoryIcon.png
  src/assets/ClothesCategoryIcon.png
  src/assets/ElectronicsCategoryIcon.png
  src/assets/FashionCategoryIcon.png
  src/assets/FoodCategoryIcon.png
  src/assets/GreyStarIcon.png
  src/assets/HobbyCategoryIcon.png
  src/assets/InteriorCategoryIcon.png
  src/assets/LifeCategoryIcon.png
  src/assets/SearchIcon.png
  src/assets/SportCategoryIcon.png
  src/assets/YellowStarIcon.png
  src/components/Category.jsx
  src/components/CategoryList.jsx
  src/components/Dropdown.jsx
  src/components/Item.jsx
  src/constants/Paths.jsx
  src/pages/ItemPage.jsx
  src/pages/LoginPage.jsx
  src/pages/ShopPage.jsx
  src/pages/SignupPage.jsx
Labels: design

#27 [CHORE] API 설정
  .gitignore
  package-lock.json
  package.json
  src/apis/api.js
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
Labels: enhancement

#26 [DESIGN] 메인페이지, 설정페이지, 알람페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Alarm.png
  src/assets/Alarm_on.png
  src/assets/Logo.png
  src/assets/MainSpeechBubble.png
  src/assets/PayIcon.png
  src/assets/PayRecordB.png
  src/assets/PayToss.png
  src/assets/Profile.png
  src/assets/ReviewIcon.png
  src/assets/Setting.png
  src/assets/SettingDropDown.png
  src/assets/SettingDropUp.png
  src/assets/ShoppingB.png
  src/assets/ThinkingB.png
  src/assets/Yuno.png
  src/assets/yuno.gif
  src/components/Header.jsx
  src/components/LineChart.jsx
  src/components/PayAlarm.jsx
  src/components/PieChart.jsx
  src/components/ReviewAlarm.jsx
  src/constants/Paths.jsx
  src/pages/AlarmPage.jsx
  src/pages/ItemPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/SettingPage.jsx
  src/pages/ShopPage.jsx
  src/pages/SignupPage.jsx
  src/styles/style.css
Labels: design

#29 [Design] Component 디자인 수정
  src/components/Button.jsx
  src/components/Header.jsx
  src/pages/SignupPage.jsx
Labels: design

#23 [DESIGN] setup 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Guidebook.png
  src/assets/MoneyIcon.png
  src/assets/TimeIcon.png
  src/assets/YunoFlower.png
  src/assets/YunoHeart.png
  src/assets/YunoLogo.png
  src/assets/YunoWarning.png
  src/constants/Paths.jsx
  src/pages/SetupCompletePage.jsx
  src/pages/SetupPage.jsx
  src/pages/WelcomePage.jsx
Labels: design

#32 [DESIGN] 결제 페이지, 결제완료 페이지 구현
  public/favicon.ico
  src/App.jsx
  src/assets/BigAngryBubble.png
  src/assets/BigAngryYuno.gif
  src/assets/BigAngryYuno.png
  src/assets/Check.png
  src/assets/GoodPayYuno.gif
  src/assets/GoodPayYuno.png
  src/assets/GreenCheck.png
  src/assets/MediumAngryBubble.png
  src/assets/MediumAngryYuno.gif
  src/assets/MediumAngryYuno.png
  src/assets/SmallAngryBubble.png
  src/assets/SmallAngryYuno.gif
  src/assets/SmallAngryYuno.png
  src/assets/SmallYuno.png
  src/assets/TossAccountIcon.png
  src/assets/TossPayIcon.png
  src/components/ItemInfo.jsx
  src/constants/Paths.jsx
  src/pages/MainPage.jsx
  src/pages/PaidPage.jsx
  src/pages/PayPage.jsx
  src/pages/SettingPage.jsx
  tailwind.config.js
Labels: design

#34 [FEATURE] Item API 연동
  src/components/CategoryList.jsx
  src/components/Dropdown.jsx
  src/constants/Paths.jsx
  src/pages/ItemPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/ShopPage.jsx
  src/pages/SignupPage.jsx
Labels: feature

#36 [DESIGN] 결제 페이지, 결제완료 페이지 구현
  src/App.jsx
  src/assets/Paper.png
  src/assets/Pencil.png
  src/components/ProgressBar.jsx
  src/constants/Paths.jsx
  src/pages/DiaryEditPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/MainPage.jsx
  src/pages/PayPage.jsx
  src/pages/PayRecordPage.jsx
  src/pages/ThinkPayPage.jsx
Labels: design

#39 [FEATURE] 메인 페이지 API 연동 및 기능 구현
  src/assets/BlackCat.png
  src/assets/CutYunoHeart.png
  src/components/CategoryList.jsx
  src/components/LineChart.jsx
  src/components/PayAlarm.jsx
  src/components/PieChart.jsx
  src/components/ReviewAlarm.jsx
  src/constants/Paths.jsx
  src/pages/AlarmPage.jsx
  src/pages/MainPage.jsx
  src/pages/PayPage.jsx
  src/pages/SettingPage.jsx
Labels: feature

#40 [FEATURE] 초기세팅 api 연동
  src/constants/Paths.jsx
  src/pages/LoginPage.jsx
  src/pages/SetupCompletePage.jsx
  src/pages/SetupPage.jsx
  src/pages/WelcomePage.jsx
Labels: feature

#43 [FEATURE] 소비일기 API연동
  src/constants/Paths.jsx
  src/pages/DiaryEditPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/MainPage.jsx
  src/pages/PayRecordPage.jsx
Labels: feature

#44 [FEATURE] 생각 중인 소비 페이지, 결제 페이지 API 연동 및 구현
  src/App.jsx
  src/components/Dropdown.jsx
  src/components/ItemInfo.jsx
  src/components/ProgressBar.jsx
  src/constants/Paths.jsx
  src/pages/AlarmPage.jsx
  src/pages/ItemPage.jsx
  src/pages/MainPage.jsx
  src/pages/PaidPage.jsx
  src/pages/PayFromItemPage.jsx
  src/pages/PayPage.jsx
  src/pages/ShopPage.jsx
  src/pages/ThinkPayPage.jsx
Labels: feature

#45 [FIX] 결제 기록, 소비 일기 페이지 디자인 수정 및 API 경로 수정
  src/pages/DiaryEditPage.jsx
  src/pages/DiaryPage.jsx
  src/pages/PayRecordPage.jsx
Labels: fix
